<a href="https://colab.research.google.com/github/Lotfullah21/Algorithms_AI/blob/main/Perceptroon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np

In [164]:
def perceptron_update(features_matrix,labels,theta, theta_0):

  if labels*(np.dot(theta, features_matrix) + theta_0 ) <=0:
    theta = theta + labels*features_matrix
    theta_0 = theta_0 + label
  return theta, theta_0  

theta = np.array([0,0])
# theta = theta.reshape(-1,1)
theta_0 = 0
feature = np.array([0.5- (np.sqrt(3)/2),0.5 + (np.sqrt(3)/2)])
label = 1

perceptron_update(feature,label,theta, theta_0)

(array([-0.3660254,  1.3660254]), 1)

In [169]:
def Perceptron(feature_matrix, labels, T):

    (nsamples, nfeatures) = feature_matrix.shape
    theta = np.zeros(nfeatures)
    order = feature_matrix.shape[0]
    theta_0 = 0.0
    for t in range(T):
        for i in range(order):
            theta, theta_0 = perceptron_update(
                feature_matrix[i], labels[i], theta, theta_0)
    return (theta, theta_0)

In [166]:
theta = np.array([[0,0]])
# theta = theta.reshape(-1,1)
theta_0 = 0
feature_matrix = np.array([[0.5- (np.sqrt(3)/2), 0.5 + (np.sqrt(3)/2)]])
labels = np.array([[1]])
T = feature_matrix.shape[0]
labels.shape[0]

1

In [167]:
Perceptron(feature_matrix, labels, T)

(array([-0.3660254,  1.3660254]), 1.0)

In [112]:
theta = np.array([5,5])
x = feature_matrix
x.shape
new_x = x.reshape(2,8)

new_x.shape
print("new_X",new_x.shape)
print ("x",x.shape)
denominator = np.dot(x,new_x)
denominator
total = denominator.sum()
print(total)

new_X (2, 8)
x (8, 2)
40.5


In [100]:
def perceptron_update(features_matrix,labels,theta):

  if labels*(np.dot(theta, features_matrix) + theta_0 ) <=0:
    theta = theta + labels*features_matrix
    # theta_0 = theta_0 + label
  return theta

theta = np.array([1,-1])
# theta = theta.reshape(-1,1)
theta_0 = 1
feature = np.array([1,3])
label = 1

perceptron_update(feature,label,theta)

array([2, 2])

## Without offset

In [101]:
def perceptron(feature_matrix, labels, T):
    """
    Runs the full perceptron algorithm on a given set of data. Runs T
    iterations through the data set, there is no need to worry about
    stopping early.

    NOTE: Please use the previously implemented functions when applicable.
    Do not copy paste code from previous parts.

    Args:
        feature_matrix -  A numpy matrix describing the given data. Each row
            represents a single data point.
        labels - A numpy array where the kth element of the array is the
            correct classification of the kth row of the feature matrix.
        T - An integer indicating how many times the perceptron algorithm
            should iterate through the feature matrix.

    Returns: A tuple where the first element is a numpy array with the value of
    theta, the linear classification parameter, after T iterations through the
    feature matrix and the second element is a real number with the value of
    theta_0, the offset classification parameter, after T iterations through
    the feature matrix.
    """
    (nsamples, nfeatures) = feature_matrix.shape
    theta = np.zeros(nfeatures)
    order = feature_matrix.shape[0]
    # theta_0 = 0.0
    for t in range(T):
        for i in range(order):
            theta = perceptron_update( feature_matrix[i], labels[i], theta)
    return (theta)

In [ ]:
feature_matrix = np.array([[1,1],[2,3],[3,4],[-0.5,-0.5],[-1,-2],[-2,-3],[-3,-4],[-4,-3]])
labels = np.array([[1],[1],[1],[-1],[-1],[-1],[-1],[-1]])
T = feature_matrix.shape[0]
labels.shape[0]

In [170]:
perceptron(feature_matrix, labels, T)

(array([-0.3660254,  1.3660254]), 1.0)

In [116]:
theta = np.array([1.5,1.5])
x = feature_matrix
x.shape
new_x = x.reshape(2,8)

new_x.shape
print("new_X",new_x.shape)
print ("x",x.shape)
denominator = np.dot(x,new_x)
total = denominator.sum()
print(total)

new_X (2, 8)
x (8, 2)
40.5


In [141]:
print("theta", theta.shape)
print("new_X",new_x.shape)
print ("x",x.shape)
theta = np.array([[1.5,1.5]])
x = feature_matrix
numerator = new_theta * new_x

# numerator.sum()
suma = numerator.sum()
print(suma)
print(numerator)

theta (1, 2)
new_X (2, 8)
x (8, 2)
-13.5
[[ 1.5   1.5   3.    4.5   4.5   6.   -0.75 -0.75]
 [-1.5  -3.   -3.   -4.5  -4.5  -6.   -6.   -4.5 ]]


In [132]:
numerator = np.dot(theta , new_x)
# numerator.sum()
numerator

array([[ 0.  , -1.5 ,  0.  ,  0.  ,  0.  ,  0.  , -6.75, -5.25]])

In [133]:
numerator.sum()

-13.5

In [150]:
|x = np.array([[0.5, -np.sqrt(3)/2], [np.sqrt(3)/2, 0.5]])
y = np.array([[2],[3]])
print(x.shape)
print(y.shape)
z = np.matmul(x,y)
z

(2, 2)
(2, 1)


array([[-1.59807621],
       [ 3.23205081]])